version: '3'

services:
  db:
    image: postgres:9.6.15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'

  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379

  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    restart: always
    ports:
      - 80:80