# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-30 15:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'Чек для клиента'), ('K', 'Чек для кухни')], max_length=1)),
                ('order', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('N', 'Новый чек'), ('C', 'Отрендеренный чек'), ('P', 'Отпечатанный чек')], default='N', max_length=1)),
                ('pdf_file', models.FileField(default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('api_key', models.CharField(max_length=20, unique=True)),
                ('check_type', models.CharField(choices=[('C', 'Чек для клиента'), ('K', 'Чек для кухни')], max_length=1)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='printer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.Printer'),
        ),
    ]
